// Nivel 2 del módulo Fundamentos: Práctica de fundamentos.
// Mismos temas que el nivel 1 (fundamentosData.js), pero cada ejercicio pide
// leer un enunciado con contexto y decidir qué hacer con los datos.
// Hay pocos de salida y variables y más de los temas que piden razonar.

export const EJERCICIOS_PRACTICA = [
  /* ── Salida y variables ── */
  {
    numero: 1, tema: 'salida-y-variables', nivel: 2,
    titulo: 'El recibo de la tienda',
    resumen: 'Varias cuentas encadenadas con variables.',
    descripcion: [
      'Una tienda vende cuadernos a 3500 pesos. Un cliente lleva 4 y la tienda le descuenta 2000 pesos del total por ser cliente frecuente.',
      'Guarda el precio, la cantidad y el descuento en variables. Calcula el subtotal (antes del descuento) y el total a pagar, y muéstralos con el formato del ejemplo.',
    ],
    entrada: 'Este ejercicio no tiene entrada.',
    salida: 'Dos líneas: "Subtotal: " seguido del subtotal, y "Total: " seguido del total a pagar.',
    ejemplos: [{ entrada: '', salida: 'Subtotal: 14000\nTotal: 12000' }],
  },
  {
    numero: 2, tema: 'salida-y-variables', nivel: 2,
    titulo: 'Rotación de tres',
    resumen: 'Mover tres valores sin perder ninguno.',
    descripcion: [
      'Tres variables empiezan así: a vale 1, b vale 2 y c vale 3.',
      'Rota sus contenidos hacia la izquierda: a debe quedar con lo que tenía b, b con lo que tenía c, y c con lo que tenía a al principio. Muestra a, b y c después de la rotación.',
    ],
    entrada: 'Este ejercicio no tiene entrada.',
    salida: 'Tres líneas: el valor final de a, el de b y el de c.',
    ejemplos: [{ entrada: '', salida: '2\n3\n1' }],
  },

  /* ── Entrada y operaciones ── */
  {
    numero: 3, tema: 'entrada-y-operaciones', nivel: 2,
    titulo: 'El cajero entrega billetes',
    resumen: 'Descomponer una cantidad con cocientes y residuos.',
    descripcion: [
      'Un cajero automático solo tiene billetes de 50000, de 10000 y de 1000 pesos, y siempre entrega la menor cantidad posible de billetes.',
      'Lee el monto que pide el cliente e indica cuántos billetes de cada valor recibe. Primero se usan los billetes más grandes.',
    ],
    entrada: 'Una línea con el monto: un entero positivo múltiplo de 1000.',
    salida: 'Tres líneas: la cantidad de billetes de 50000, de 10000 y de 1000, en ese orden.',
    ejemplos: [{ entrada: '187000', salida: '3\n3\n7' }, { entrada: '9000', salida: '0\n0\n9' }, { entrada: '60000', salida: '1\n1\n0' }],
  },
  {
    numero: 4, tema: 'entrada-y-operaciones', nivel: 2,
    titulo: 'El cronómetro',
    resumen: 'De segundos a horas, minutos y segundos.',
    descripcion: [
      'Un cronómetro deportivo guarda el tiempo de cada atleta como una sola cantidad de segundos, pero en la pantalla debe verse en horas, minutos y segundos.',
      'Lee la cantidad de segundos y conviértela. Los minutos y los segundos del resultado nunca pasan de 59.',
    ],
    entrada: 'Una línea con un entero mayor o igual que cero: los segundos.',
    salida: 'Tres líneas: las horas, los minutos y los segundos.',
    ejemplos: [{ entrada: '3725', salida: '1\n2\n5' }, { entrada: '59', salida: '0\n0\n59' }, { entrada: '7200', salida: '2\n0\n0' }],
  },
  {
    numero: 5, tema: 'entrada-y-operaciones', nivel: 2,
    titulo: 'Promedio sin decimales',
    resumen: 'Un promedio que se trunca.',
    descripcion: [
      'En un colegio las notas van de 0 a 50 y el boletín solo muestra números enteros.',
      'Lee las tres notas de un estudiante y muestra su promedio. Si el promedio tiene decimales, se descartan: no se redondea hacia arriba.',
    ],
    entrada: 'Tres líneas, cada una con una nota entera entre 0 y 50.',
    salida: 'Una línea con el promedio sin decimales.',
    ejemplos: [{ entrada: '35\n40\n42', salida: '39' }, { entrada: '30\n30\n31', salida: '30' }, { entrada: '50\n49\n49', salida: '49' }],
  },
  {
    numero: 6, tema: 'entrada-y-operaciones', nivel: 3,
    titulo: 'Galones de pintura',
    resumen: 'Redondear hacia arriba usando solo enteros.',
    descripcion: [
      'Vas a pintar una pared rectangular. Un galón de pintura alcanza para 12 metros cuadrados y la ferretería solo vende galones completos.',
      'Lee el ancho y el alto de la pared en metros y calcula cuántos galones hay que comprar para que la pintura alcance. Si sobra pintura, no importa; lo que no puede pasar es que falte.',
    ],
    entrada: 'Dos líneas: el ancho y el alto de la pared, enteros positivos.',
    salida: 'Una línea con la cantidad de galones que se deben comprar.',
    ejemplos: [{ entrada: '5\n3', salida: '2' }, { entrada: '4\n3', salida: '1' }, { entrada: '1\n1', salida: '1' }, { entrada: '6\n4', salida: '2' }],
    pistaConcepto: 'Para redondear una división hacia arriba puedes sumarle al dividendo el divisor menos uno antes de truncar.',
  },
  {
    numero: 7, tema: 'entrada-y-operaciones', nivel: 2,
    titulo: 'Las tres cifras',
    resumen: 'Separar un número en centenas, decenas y unidades.',
    descripcion: [
      'Lee un número de exactamente tres cifras y sepáralo en sus cifras.',
      'Con ellas calcula dos resultados: la suma de las tres cifras y el producto de las tres cifras.',
    ],
    entrada: 'Una línea con un entero entre 100 y 999.',
    salida: 'Dos líneas: la suma de las cifras y el producto de las cifras.',
    ejemplos: [{ entrada: '123', salida: '6\n6' }, { entrada: '405', salida: '9\n0' }, { entrada: '999', salida: '27\n729' }],
  },
  {
    numero: 8, tema: 'entrada-y-operaciones', nivel: 3,
    titulo: 'Duración del viaje',
    resumen: 'Una regla de tres con resultado en horas y minutos.',
    descripcion: [
      'Un bus recorre una distancia a velocidad constante. La empresa quiere anunciar cuánto dura el viaje en horas y minutos.',
      'Lee la distancia en kilómetros y la velocidad en kilómetros por hora. Calcula primero la duración total en minutos, descartando la fracción de minuto que sobre, y luego exprésala en horas y minutos.',
    ],
    entrada: 'Dos líneas: la distancia y la velocidad, enteros positivos.',
    salida: 'Dos líneas: las horas completas y los minutos restantes.',
    ejemplos: [{ entrada: '150\n60', salida: '2\n30' }, { entrada: '100\n80', salida: '1\n15' }, { entrada: '50\n70', salida: '0\n42' }],
  },
  {
    numero: 9, tema: 'entrada-y-operaciones', nivel: 3,
    titulo: 'Reparto de dulces',
    resumen: 'Cociente, residuo y lo que falta para el siguiente.',
    descripcion: [
      'Una profesora reparte dulces entre sus estudiantes en partes iguales, entregando la mayor cantidad posible a cada uno. Los que no alcanzan para otra ronda completa se quedan en la bolsa.',
      'Lee cuántos dulces hay y cuántos estudiantes son. Indica cuántos recibe cada estudiante, cuántos quedan en la bolsa y cuántos dulces más tendría que conseguir la profesora para que a cada estudiante le toque exactamente uno más.',
    ],
    entrada: 'Dos líneas: la cantidad de dulces (mayor o igual que cero) y la cantidad de estudiantes (mayor que cero).',
    salida: 'Tres líneas: dulces por estudiante, dulces que sobran y dulces que faltan para la siguiente ronda.',
    ejemplos: [{ entrada: '17\n5', salida: '3\n2\n3' }, { entrada: '20\n4', salida: '5\n0\n4' }, { entrada: '3\n8', salida: '0\n3\n5' }],
  },
  {
    numero: 10, tema: 'entrada-y-operaciones', nivel: 2,
    titulo: 'Edad en días',
    resumen: 'Convertir tres unidades a una sola.',
    descripcion: [
      'Una aplicación de salud quiere mostrar la edad de sus usuarios en días.',
      'Lee la edad de una persona en años, meses y días. Para simplificar, la aplicación considera que todos los años tienen 365 días y todos los meses tienen 30. Calcula el total de días.',
    ],
    entrada: 'Tres líneas: los años, los meses (entre 0 y 11) y los días (entre 0 y 29).',
    salida: 'Una línea con la edad en días.',
    ejemplos: [{ entrada: '1\n2\n3', salida: '428' }, { entrada: '20\n0\n0', salida: '7300' }, { entrada: '0\n11\n29', salida: '359' }],
  },

  /* ── Condicionales ── */
  {
    numero: 11, tema: 'condicionales', nivel: 3,
    titulo: 'Horas extra',
    resumen: 'Un pago que cambia a partir de cierto límite.',
    descripcion: [
      'En una fábrica la jornada semanal normal es de 40 horas. Cada hora que un empleado trabaja por encima de esas 40 se le paga al doble del valor normal.',
      'Lee las horas que trabajó un empleado en la semana y el valor de una hora normal. Calcula cuánto se le debe pagar.',
    ],
    entrada: 'Dos líneas: las horas trabajadas y el valor de la hora, enteros positivos.',
    salida: 'Una línea con el pago de la semana.',
    ejemplos: [{ entrada: '45\n10000', salida: '500000' }, { entrada: '40\n5000', salida: '200000' }, { entrada: '10\n8000', salida: '80000' }],
  },
  {
    numero: 12, tema: 'condicionales', nivel: 3,
    titulo: 'Descuento por volumen',
    resumen: 'Tres tramos con porcentajes distintos.',
    descripcion: [
      'Un almacén premia las compras grandes: si el total es de 200000 pesos o más, descuenta el 20 %; si es de 100000 o más pero no llega a 200000, descuenta el 10 %; por debajo de 100000 no hay descuento.',
      'Lee el total de la compra y muestra cuánto paga el cliente después del descuento.',
    ],
    entrada: 'Una línea con el total de la compra: un entero positivo múltiplo de 10.',
    salida: 'Una línea con el valor a pagar.',
    ejemplos: [{ entrada: '250000', salida: '200000' }, { entrada: '100000', salida: '90000' }, { entrada: '99990', salida: '99990' }, { entrada: '200000', salida: '160000' }],
  },
  {
    numero: 13, tema: 'condicionales', nivel: 3,
    titulo: '¿Se puede armar el triángulo?',
    resumen: 'Validar los datos antes de clasificarlos.',
    descripcion: [
      'Tres palitos solo forman un triángulo si cada uno es más corto que la suma de los otros dos. Si esa condición falla aunque sea para un palito, no se puede cerrar la figura.',
      'Lee las tres longitudes. Si no forman un triángulo, dilo. Si lo forman, clasifícalo: equilátero cuando los tres lados son iguales, isósceles cuando exactamente dos lo son y escaleno cuando los tres son distintos.',
    ],
    entrada: 'Tres líneas, cada una con un entero positivo.',
    salida: 'Una línea con No es triangulo, Equilatero, Isosceles o Escaleno, sin tildes.',
    ejemplos: [{ entrada: '1\n2\n3', salida: 'No es triangulo' }, { entrada: '2\n2\n3', salida: 'Isosceles' }, { entrada: '3\n4\n5', salida: 'Escaleno' }, { entrada: '6\n6\n6', salida: 'Equilatero' }, { entrada: '10\n2\n2', salida: 'No es triangulo' }],
  },
  {
    numero: 14, tema: 'condicionales', nivel: 2,
    titulo: 'Grupo de edad',
    resumen: 'Rangos consecutivos sin huecos.',
    descripcion: [
      'Un centro de salud organiza a sus pacientes por edad: hasta los 11 años son niños, de 12 a 17 son adolescentes, de 18 a 59 son adultos y desde los 60 son adultos mayores.',
      'Lee la edad de un paciente y muestra a qué grupo pertenece.',
    ],
    entrada: 'Una línea con un entero mayor o igual que cero: la edad.',
    salida: 'Una línea con Nino, Adolescente, Adulto o Adulto mayor, escrito tal cual.',
    ejemplos: [{ entrada: '11', salida: 'Nino' }, { entrada: '12', salida: 'Adolescente' }, { entrada: '59', salida: 'Adulto' }, { entrada: '60', salida: 'Adulto mayor' }],
  },
  {
    numero: 15, tema: 'condicionales', nivel: 3,
    titulo: 'Aprobar con condiciones',
    resumen: 'Dos requisitos que deben cumplirse a la vez.',
    descripcion: [
      'En una materia se presentan tres exámenes con nota de 0 a 50. Para aprobar no basta con un buen promedio: el promedio de los tres debe ser de 30 o más y, además, ninguna nota puede ser menor que 20.',
      'Lee las tres notas e indica si el estudiante aprueba.',
    ],
    entrada: 'Tres líneas, cada una con una nota entera entre 0 y 50.',
    salida: 'Una línea con Aprobado o Reprobado.',
    ejemplos: [{ entrada: '30\n30\n30', salida: 'Aprobado' }, { entrada: '50\n50\n10', salida: 'Reprobado' }, { entrada: '20\n30\n30', salida: 'Reprobado' }, { entrada: '20\n30\n40', salida: 'Aprobado' }],
    pistaConcepto: 'Comparar el promedio con 30 es lo mismo que comparar la suma con 90, y así no aparecen decimales.',
  },
  {
    numero: 16, tema: 'condicionales', nivel: 3,
    titulo: 'El del medio',
    resumen: 'Ni el mayor ni el menor.',
    descripcion: [
      'Tres amigos comparan sus estaturas en centímetros y quieren saber quién queda en el medio: el que no es ni el más alto ni el más bajo.',
      'Lee tres números enteros distintos y muestra el que queda en el medio al ordenarlos.',
    ],
    entrada: 'Tres líneas, cada una con un entero. Los tres son distintos entre sí.',
    salida: 'Una línea con el valor del medio.',
    ejemplos: [{ entrada: '3\n9\n5', salida: '5' }, { entrada: '10\n1\n7', salida: '7' }, { entrada: '-2\n-8\n0', salida: '-2' }],
  },
  {
    numero: 17, tema: 'condicionales', nivel: 4,
    titulo: 'Fecha válida',
    resumen: 'Cada mes tiene su propio límite.',
    descripcion: [
      'Un formulario pide el día y el mes de nacimiento y debe rechazar las fechas que no existen, como el 31 de abril o el mes 13.',
      'Lee un día y un mes y decide si la fecha existe. El año no es bisiesto, así que febrero tiene 28 días. Abril, junio, septiembre y noviembre tienen 30; los demás, 31.',
    ],
    entrada: 'Dos líneas: el día y el mes, ambos enteros.',
    salida: 'Una línea con Valida o Invalida, sin tildes.',
    ejemplos: [{ entrada: '31\n4', salida: 'Invalida' }, { entrada: '28\n2', salida: 'Valida' }, { entrada: '29\n2', salida: 'Invalida' }, { entrada: '31\n12', salida: 'Valida' }, { entrada: '0\n5', salida: 'Invalida' }, { entrada: '10\n13', salida: 'Invalida' }],
  },
  {
    numero: 18, tema: 'condicionales', nivel: 3,
    titulo: 'El parqueadero',
    resumen: 'Una tarifa con primera hora, adicionales y tope.',
    descripcion: [
      'Un parqueadero cobra 3000 pesos por la primera hora y 2000 por cada hora adicional. Para no espantar a quienes dejan el carro todo el día, nunca cobra más de 15000 pesos.',
      'Lee cuántas horas estuvo un carro y calcula cuánto debe pagar.',
    ],
    entrada: 'Una línea con un entero mayor o igual que 1: las horas.',
    salida: 'Una línea con el valor a pagar.',
    ejemplos: [{ entrada: '1', salida: '3000' }, { entrada: '3', salida: '7000' }, { entrada: '7', salida: '15000' }, { entrada: '10', salida: '15000' }],
  },
  {
    numero: 19, tema: 'condicionales', nivel: 4,
    titulo: 'Piedra, papel o tijera',
    resumen: 'Muchas combinaciones, tres resultados.',
    descripcion: [
      'Dos jugadores, A y B, eligen cada uno un número: 1 es piedra, 2 es papel y 3 es tijera. La piedra le gana a la tijera, la tijera le gana al papel y el papel le gana a la piedra. Si eligen lo mismo, empatan.',
      'Lee la jugada de A y luego la de B, y anuncia el resultado.',
    ],
    entrada: 'Dos líneas: la jugada de A y la jugada de B, cada una un entero entre 1 y 3.',
    salida: 'Una línea con Gana A, Gana B o Empate.',
    ejemplos: [{ entrada: '1\n3', salida: 'Gana A' }, { entrada: '2\n3', salida: 'Gana B' }, { entrada: '2\n2', salida: 'Empate' }, { entrada: '1\n2', salida: 'Gana B' }, { entrada: '3\n2', salida: 'Gana A' }],
  },

  /* ── Selección múltiple ── */
  {
    numero: 20, tema: 'segun', nivel: 3,
    titulo: 'Costo del envío',
    resumen: 'Un Segun y una condición extra.',
    descripcion: [
      'Una empresa de mensajería cobra según la zona de destino: 5000 pesos para la zona 1, 8000 para la zona 2, 12000 para la zona 3 y 20000 para la zona 4. Si el paquete pesa más de 5 kilos, se suman 3000 pesos sin importar la zona.',
      'Lee la zona y el peso del paquete y calcula el costo del envío. Si la zona no existe, no se calcula nada y se avisa.',
    ],
    entrada: 'Dos líneas: la zona y el peso en kilos, ambos enteros.',
    salida: 'Una línea con el costo del envío, o con el texto Zona invalida.',
    ejemplos: [{ entrada: '1\n2', salida: '5000' }, { entrada: '3\n6', salida: '15000' }, { entrada: '4\n5', salida: '20000' }, { entrada: '5\n1', salida: 'Zona invalida' }],
  },
  {
    numero: 21, tema: 'segun', nivel: 2,
    titulo: 'Estación del año',
    resumen: 'Agrupar varios valores en un mismo caso.',
    descripcion: [
      'En un país con cuatro estaciones, diciembre, enero y febrero son invierno; marzo, abril y mayo son primavera; junio, julio y agosto son verano; y septiembre, octubre y noviembre son otoño.',
      'Lee el número de un mes y muestra la estación a la que pertenece.',
    ],
    entrada: 'Una línea con un número entero.',
    salida: 'Una línea con Invierno, Primavera, Verano u Otono (sin tilde ni eñe), o con Mes invalido si el número no está entre 1 y 12.',
    ejemplos: [{ entrada: '1', salida: 'Invierno' }, { entrada: '5', salida: 'Primavera' }, { entrada: '9', salida: 'Otono' }, { entrada: '12', salida: 'Invierno' }, { entrada: '0', salida: 'Mes invalido' }],
  },
  {
    numero: 22, tema: 'segun', nivel: 3,
    titulo: 'Calculadora con símbolos',
    resumen: 'Elegir la operación con un carácter y cuidar un caso especial.',
    descripcion: [
      'Construye una calculadora que recibe dos enteros y el símbolo de la operación: + para sumar, - para restar, * para multiplicar y / para dividir. La división es entera: se descartan los decimales.',
      'Hay dos situaciones que no tienen resultado. Dividir entre cero es un error, y cualquier símbolo distinto de los cuatro anteriores no es una operación válida.',
    ],
    entrada: 'Tres líneas: el primer entero, el segundo entero (ambos mayores o iguales que cero) y el símbolo.',
    salida: 'Una línea con el resultado, con la palabra Error si se divide entre cero, o con Operacion invalida si el símbolo no se reconoce.',
    ejemplos: [{ entrada: '7\n2\n/', salida: '3' }, { entrada: '7\n0\n/', salida: 'Error' }, { entrada: '4\n5\n*', salida: '20' }, { entrada: '4\n5\n%', salida: 'Operacion invalida' }, { entrada: '3\n8\n-', salida: '-5' }],
  },
  {
    numero: 23, tema: 'segun', nivel: 3,
    titulo: 'Lo que falta del mes',
    resumen: 'Usar el Segun para obtener un dato y luego calcular.',
    descripcion: [
      'Una agenda quiere mostrar cuántos días faltan para que termine el mes.',
      'Lee el día y el mes de hoy. La fecha siempre existe. El año no es bisiesto: febrero tiene 28 días; abril, junio, septiembre y noviembre tienen 30; y los demás meses, 31. Calcula cuántos días quedan después de hoy para llegar al último día del mes.',
    ],
    entrada: 'Dos líneas: el día y el mes, que forman una fecha válida.',
    salida: 'Una línea con los días que faltan para el fin de mes.',
    ejemplos: [{ entrada: '28\n2', salida: '0' }, { entrada: '1\n1', salida: '30' }, { entrada: '15\n4', salida: '15' }],
  },
  {
    numero: 24, tema: 'segun', nivel: 4,
    titulo: 'El cajero automático',
    resumen: 'Un menú donde una opción puede fallar.',
    descripcion: [
      'Un cajero ofrece tres opciones. La opción 1 consulta el saldo. La opción 2 retira dinero, pero solo si el saldo alcanza. La opción 3 consigna dinero en la cuenta.',
      'Lee el saldo actual, la opción elegida y un monto. El monto siempre viene en la entrada, aunque la opción 1 no lo use. Muestra el saldo que queda después de la operación.',
    ],
    entrada: 'Tres líneas: el saldo, la opción y el monto, todos enteros mayores o iguales que cero.',
    salida: 'Una línea con el saldo final, con Fondos insuficientes si se intenta retirar más de lo que hay, o con Opcion invalida si la opción no es 1, 2 ni 3.',
    ejemplos: [{ entrada: '50000\n1\n0', salida: '50000' }, { entrada: '50000\n2\n20000', salida: '30000' }, { entrada: '50000\n2\n60000', salida: 'Fondos insuficientes' }, { entrada: '50000\n3\n5000', salida: '55000' }, { entrada: '1000\n9\n0', salida: 'Opcion invalida' }, { entrada: '8000\n2\n8000', salida: '0' }],
  },

  /* ── Ciclos Mientras y Repetir ── */
  {
    numero: 25, tema: 'ciclos-mientras', nivel: 3,
    titulo: 'Adivina el número',
    resumen: 'Un ciclo que responde a cada intento.',
    descripcion: [
      'En un juego, la máquina tiene un número secreto y el jugador intenta adivinarlo. Después de cada intento fallido la máquina da una pista: dice Mayor si el secreto es mayor que el intento, o Menor si el secreto es menor.',
      'Lee primero el número secreto y luego los intentos, uno por línea, hasta que el jugador acierte. Al acertar, muestra cuántos intentos hizo en total.',
    ],
    entrada: 'La primera línea trae el número secreto. Siguen los intentos, uno por línea; el último siempre es igual al secreto.',
    salida: 'Una línea con Mayor o Menor por cada intento fallido y, al final, una línea con "Intentos: " seguido del total.',
    ejemplos: [{ entrada: '7\n3\n9\n7', salida: 'Mayor\nMenor\nIntentos: 3' }, { entrada: '5\n5', salida: 'Intentos: 1' }],
  },
  {
    numero: 26, tema: 'ciclos-mientras', nivel: 3,
    titulo: 'El camino hasta el uno',
    resumen: 'Repetir una regla sin saber cuántas veces.',
    descripcion: [
      'Toma un entero positivo y aplica esta regla una y otra vez: si el número es par, divídelo entre 2; si es impar, multiplícalo por 3 y súmale 1. Siempre se termina llegando al 1.',
      'Lee un número y cuenta cuántas veces hay que aplicar la regla para llegar a 1. Si el número ya es 1, no hay que aplicarla ninguna vez.',
    ],
    entrada: 'Una línea con un entero entre 1 y 1000.',
    salida: 'Una línea con la cantidad de pasos.',
    ejemplos: [{ entrada: '6', salida: '8' }, { entrada: '1', salida: '0' }, { entrada: '7', salida: '16' }],
  },
  {
    numero: 27, tema: 'ciclos-mientras', nivel: 4,
    titulo: 'Baldosas cuadradas',
    resumen: 'El máximo común divisor con un ciclo.',
    descripcion: [
      'Se quiere cubrir un piso rectangular con baldosas cuadradas, todas iguales y sin cortar ninguna. Para usar pocas baldosas conviene que sean lo más grandes posible.',
      'Lee el largo y el ancho del piso en centímetros y muestra el lado de la baldosa cuadrada más grande que lo cubre exactamente. Ese lado es el mayor número que divide a las dos medidas sin dejar residuo.',
    ],
    entrada: 'Dos líneas: el largo y el ancho, enteros positivos.',
    salida: 'Una línea con el lado de la baldosa.',
    ejemplos: [{ entrada: '48\n18', salida: '6' }, { entrada: '17\n5', salida: '1' }, { entrada: '20\n20', salida: '20' }],
    pistaConcepto: 'Si reemplazas el mayor de dos números por el residuo de dividirlo entre el menor, el divisor común más grande no cambia.',
  },
  {
    numero: 28, tema: 'ciclos-mientras', nivel: 3,
    titulo: 'La alcancía',
    resumen: 'Un acumulador cuyo aporte también cambia.',
    descripcion: [
      'Sara ahorra para comprar una bicicleta. El primer mes guarda cierta cantidad, y cada mes siguiente guarda 5000 pesos más que el mes anterior.',
      'Lee el precio de la bicicleta y lo que Sara guarda el primer mes. Calcula en cuántos meses tendrá ahorrado el precio completo o más.',
    ],
    entrada: 'Dos líneas: el precio de la bicicleta y el ahorro del primer mes, enteros positivos.',
    salida: 'Una línea con la cantidad de meses.',
    ejemplos: [{ entrada: '100000\n20000', salida: '4' }, { entrada: '10000\n10000', salida: '1' }, { entrada: '50000\n10000', salida: '4' }],
  },
  {
    numero: 29, tema: 'ciclos-mientras', nivel: 4,
    titulo: 'Resumen de notas',
    resumen: 'Tres resultados a partir de una lista sin tamaño conocido.',
    descripcion: [
      'Un profesor dicta las notas de su curso una por una y, cuando termina, dice -1. Las notas son enteros entre 0 y 50; el -1 no es una nota.',
      'Lee las notas y muestra cuántas fueron, cuál fue la más alta y el promedio sin decimales. Si el profesor dice -1 de entrada, no hay nada que resumir.',
    ],
    entrada: 'Varias líneas con una nota cada una. La última línea siempre es -1.',
    salida: 'Tres líneas: la cantidad de notas, la nota más alta y el promedio truncado. Si no hubo notas, una sola línea con el texto Sin datos.',
    ejemplos: [{ entrada: '30\n40\n50\n-1', salida: '3\n50\n40' }, { entrada: '-1', salida: 'Sin datos' }, { entrada: '45\n-1', salida: '1\n45\n45' }, { entrada: '10\n11\n-1', salida: '2\n11\n10' }],
  },
  {
    numero: 30, tema: 'ciclos-mientras', nivel: 3,
    titulo: 'Número capicúa',
    resumen: 'Invertir un número y compararlo con el original.',
    descripcion: [
      'Un número es capicúa cuando se lee igual de izquierda a derecha que de derecha a izquierda, como 121 o 4554.',
      'Lee un entero positivo e indica si es capicúa. Recuerda que al invertirlo vas a modificar el número, así que necesitas conservar el original para comparar.',
    ],
    entrada: 'Una línea con un entero mayor o igual que 1.',
    salida: 'Una línea con Capicua o No capicua, sin tilde.',
    ejemplos: [{ entrada: '121', salida: 'Capicua' }, { entrada: '123', salida: 'No capicua' }, { entrada: '7', salida: 'Capicua' }, { entrada: '1221', salida: 'Capicua' }],
  },
  {
    numero: 31, tema: 'ciclos-mientras', nivel: 4,
    titulo: 'Unos en binario',
    resumen: 'Dividir entre dos una y otra vez.',
    descripcion: [
      'Para escribir un número en binario se divide entre 2 repetidamente: cada residuo es una cifra binaria y el cociente pasa a la siguiente división, hasta que el cociente llega a cero. Por ejemplo, 5 en binario es 101.',
      'Lee un entero positivo y muestra cuántas cifras binarias valen 1 y cuántas cifras tiene en total su representación binaria.',
    ],
    entrada: 'Una línea con un entero entre 1 y 1000000.',
    salida: 'Dos líneas: la cantidad de unos y la cantidad total de cifras binarias.',
    ejemplos: [{ entrada: '5', salida: '2\n3' }, { entrada: '8', salida: '1\n4' }, { entrada: '1', salida: '1\n1' }, { entrada: '255', salida: '8\n8' }],
  },
  {
    numero: 32, tema: 'ciclos-mientras', nivel: 4,
    titulo: 'El tanque con fuga',
    resumen: 'El orden de los pasos dentro del ciclo importa.',
    descripcion: [
      'Un tanque vacío se llena con una manguera, pero tiene una fuga. Cada minuto ocurre lo mismo: primero entran los litros de la manguera y, si con eso el tanque todavía no está lleno, después se escapan los litros de la fuga.',
      'Lee la capacidad del tanque, los litros que entran por minuto y los litros que se escapan por minuto. Entra más agua de la que se escapa. Calcula en qué minuto se llena el tanque, es decir, cuándo el agua alcanza o supera la capacidad.',
    ],
    entrada: 'Tres líneas: la capacidad, los litros que entran y los litros que se escapan, enteros positivos.',
    salida: 'Una línea con el minuto en que el tanque se llena.',
    ejemplos: [{ entrada: '10\n4\n1', salida: '3' }, { entrada: '5\n5\n1', salida: '1' }, { entrada: '20\n6\n2', salida: '5' }],
  },

  /* ── Ciclo Para ── */
  {
    numero: 33, tema: 'ciclo-para', nivel: 3,
    titulo: 'Escalera de asteriscos',
    resumen: 'Un ciclo dentro de otro para dibujar.',
    descripcion: [
      'Dibuja una escalera de N escalones con asteriscos: la primera línea tiene un asterisco, la segunda tiene dos, y así hasta la línea N, que tiene N.',
      'Los asteriscos de una misma línea van pegados, sin espacios entre ellos.',
    ],
    entrada: 'Una línea con un entero N entre 1 y 20.',
    salida: 'N líneas: la línea número i tiene i asteriscos seguidos.',
    ejemplos: [{ entrada: '3', salida: '*\n**\n***' }, { entrada: '1', salida: '*' }],
    pistaConcepto: 'Escribir ... Sin Saltar deja el cursor en la misma línea, para seguir escribiendo a continuación.',
  },
  {
    numero: 34, tema: 'ciclo-para', nivel: 3,
    titulo: 'Pares por un lado, impares por otro',
    resumen: 'Dos acumuladores en un mismo recorrido.',
    descripcion: [
      'Lee un entero N y recorre los números del 1 al N separándolos en dos grupos: los pares y los impares.',
      'Muestra la suma de todos los pares y la suma de todos los impares.',
    ],
    entrada: 'Una línea con un entero N mayor o igual que 1.',
    salida: 'Dos líneas: la suma de los pares y la suma de los impares.',
    ejemplos: [{ entrada: '10', salida: '30\n25' }, { entrada: '1', salida: '0\n1' }, { entrada: '7', salida: '12\n16' }],
  },
  {
    numero: 35, tema: 'ciclo-para', nivel: 4,
    titulo: 'Número perfecto',
    resumen: 'Sumar los divisores de un número.',
    descripcion: [
      'Un número es perfecto cuando es igual a la suma de sus divisores propios, es decir, de todos los números que lo dividen exactamente sin contarlo a él mismo. El 6 es perfecto porque 1 + 2 + 3 = 6.',
      'Lee un entero positivo e indica si es perfecto.',
    ],
    entrada: 'Una línea con un entero entre 1 y 10000.',
    salida: 'Una línea con Perfecto o No perfecto.',
    ejemplos: [{ entrada: '6', salida: 'Perfecto' }, { entrada: '28', salida: 'Perfecto' }, { entrada: '12', salida: 'No perfecto' }, { entrada: '1', salida: 'No perfecto' }],
  },
  {
    numero: 36, tema: 'ciclo-para', nivel: 3,
    titulo: 'La sucesión de los conejos',
    resumen: 'Cada término depende de los dos anteriores.',
    descripcion: [
      'En la sucesión de Fibonacci los dos primeros términos valen 1, y a partir del tercero cada término es la suma de los dos anteriores: 1, 1, 2, 3, 5, 8...',
      'Lee un entero N y muestra los primeros N términos de la sucesión, uno por línea.',
    ],
    entrada: 'Una línea con un entero N entre 1 y 40.',
    salida: 'N líneas con los primeros N términos.',
    ejemplos: [{ entrada: '5', salida: '1\n1\n2\n3\n5' }, { entrada: '1', salida: '1' }, { entrada: '2', salida: '1\n1' }],
  },
  {
    numero: 37, tema: 'ciclo-para', nivel: 4,
    titulo: 'Ahorro con intereses',
    resumen: 'Aplicar la misma regla año tras año.',
    descripcion: [
      'Un banco paga un interés del 10 % al final de cada año sobre lo que haya en la cuenta en ese momento. El banco solo abona pesos completos: si el interés tiene decimales, los descarta.',
      'Lee el dinero inicial y la cantidad de años que permanece en la cuenta, y muestra cuánto dinero hay al final. El interés de cada año se calcula sobre el saldo que dejó el año anterior.',
    ],
    entrada: 'Dos líneas: el dinero inicial (entero positivo) y la cantidad de años (entre 0 y 20).',
    salida: 'Una línea con el saldo final.',
    ejemplos: [{ entrada: '1000\n2', salida: '1210' }, { entrada: '1500\n3', salida: '1996' }, { entrada: '999\n1', salida: '1098' }, { entrada: '500\n0', salida: '500' }],
  },
  {
    numero: 38, tema: 'ciclo-para', nivel: 4,
    titulo: 'Todos los primos hasta N',
    resumen: 'Una prueba de primo dentro de un recorrido.',
    descripcion: [
      'Un número es primo si es mayor que 1 y sus únicos divisores son el 1 y él mismo.',
      'Lee un entero N y muestra todos los números primos desde 2 hasta N, en orden creciente y uno por línea.',
    ],
    entrada: 'Una línea con un entero N entre 2 y 500.',
    salida: 'Los números primos menores o iguales que N, uno por línea.',
    ejemplos: [{ entrada: '10', salida: '2\n3\n5\n7' }, { entrada: '2', salida: '2' }, { entrada: '20', salida: '2\n3\n5\n7\n11\n13\n17\n19' }],
  },
  {
    numero: 39, tema: 'ciclo-para', nivel: 3,
    titulo: 'El juego del Fizz Buzz',
    resumen: 'El orden de las condiciones cambia el resultado.',
    descripcion: [
      'En un juego de salón se cuenta en voz alta desde 1, pero con una regla: en lugar de los múltiplos de 3 se dice Fizz, en lugar de los múltiplos de 5 se dice Buzz, y en lugar de los que son múltiplos de 3 y de 5 a la vez se dice FizzBuzz.',
      'Lee un entero N y muestra lo que se diría al contar del 1 al N, una línea por turno.',
    ],
    entrada: 'Una línea con un entero N entre 1 y 100.',
    salida: 'N líneas: en cada una el número del turno, o Fizz, Buzz o FizzBuzz según corresponda.',
    ejemplos: [{ entrada: '5', salida: '1\n2\nFizz\n4\nBuzz' }, { entrada: '15', salida: '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz' }],
  },

  /* ── Arreglos ── */
  {
    numero: 40, tema: 'arreglos', nivel: 4,
    titulo: 'El subcampeón',
    resumen: 'Guardar los dos mejores mientras se recorre.',
    descripcion: [
      'En una competencia cada participante obtiene un puntaje distinto. El campeón es quien tiene el puntaje más alto y el subcampeón, quien tiene el segundo más alto.',
      'Lee los puntajes y muestra el del subcampeón.',
    ],
    entrada: 'La primera línea trae N (entre 2 y 100). Siguen N líneas con un puntaje entero cada una. No hay puntajes repetidos.',
    salida: 'Una línea con el segundo puntaje más alto.',
    ejemplos: [{ entrada: '5\n3\n9\n1\n7\n4', salida: '7' }, { entrada: '2\n1\n2', salida: '1' }, { entrada: '3\n-5\n-1\n-9', salida: '-5' }],
  },
  {
    numero: 41, tema: 'arreglos', nivel: 4,
    titulo: 'La fila que avanza',
    resumen: 'Rotar un arreglo varias posiciones.',
    descripcion: [
      'En una fila, cada vez que suena la campana la última persona pasa al primer puesto y las demás corren un lugar hacia atrás. A esto se le llama rotar la fila una posición a la derecha.',
      'Lee los números de la fila y cuántas veces suena la campana, y muestra cómo queda la fila. La campana puede sonar más veces que personas hay en la fila.',
    ],
    entrada: 'La primera línea trae N (entre 1 y 100). Siguen N líneas con un entero cada una: la fila de adelante hacia atrás. La última línea trae K, mayor o igual que cero: las veces que suena la campana.',
    salida: 'N líneas con la fila después de las K rotaciones, de adelante hacia atrás.',
    ejemplos: [{ entrada: '5\n1\n2\n3\n4\n5\n2', salida: '4\n5\n1\n2\n3' }, { entrada: '3\n7\n8\n9\n3', salida: '7\n8\n9' }, { entrada: '4\n1\n2\n3\n4\n5', salida: '4\n1\n2\n3' }],
  },
  {
    numero: 42, tema: 'arreglos', nivel: 4,
    titulo: '¿Está en orden?',
    resumen: 'Comparar cada elemento con su vecino.',
    descripcion: [
      'Una lista de números está en orden cuando ningún elemento es menor que el que tiene justo antes. Dos elementos iguales seguidos no rompen el orden.',
      'Lee la lista. Si está en orden, dilo. Si no, muestra la posición, contando desde 1, del primer elemento que es menor que su anterior.',
    ],
    entrada: 'La primera línea trae N (entre 1 y 100). Siguen N líneas con un entero cada una.',
    salida: 'Una línea con la palabra Ordenado, o con la posición del primer elemento fuera de orden.',
    ejemplos: [{ entrada: '4\n1\n2\n2\n5', salida: 'Ordenado' }, { entrada: '5\n1\n3\n2\n4\n0', salida: '3' }, { entrada: '1\n9', salida: 'Ordenado' }],
  },
  {
    numero: 43, tema: 'arreglos', nivel: 5,
    titulo: 'La racha más larga',
    resumen: 'Contar repeticiones seguidas y recordar el récord.',
    descripcion: [
      'Un sensor registra la temperatura cada hora. Llamamos racha a un grupo de lecturas seguidas que tienen exactamente el mismo valor. Una lectura sola ya es una racha de longitud 1.',
      'Lee las lecturas y muestra la longitud de la racha más larga.',
    ],
    entrada: 'La primera línea trae N (entre 1 y 100). Siguen N líneas con una lectura entera cada una.',
    salida: 'Una línea con la longitud de la racha más larga.',
    ejemplos: [{ entrada: '7\n1\n1\n2\n2\n2\n3\n2', salida: '3' }, { entrada: '3\n4\n5\n6', salida: '1' }, { entrada: '4\n7\n7\n7\n7', salida: '4' }],
  },
  {
    numero: 44, tema: 'arreglos', nivel: 4,
    titulo: 'Ventas de la semana',
    resumen: 'Tres preguntas sobre los mismos siete datos.',
    descripcion: [
      'Una panadería anota cuántos panes vende cada día de la semana, de lunes a domingo. Al cierre quiere saber cuánto vendió en total, cuál fue su mejor día y cuál fue el peor.',
      'Lee las siete ventas. Los días se numeran del 1 (lunes) al 7 (domingo). Si dos días empatan como el mejor o como el peor, se toma el que ocurrió primero.',
    ],
    entrada: 'Siete líneas, cada una con un entero mayor o igual que cero: las ventas de lunes a domingo.',
    salida: 'Tres líneas: el total de la semana, el número del día con más ventas y el número del día con menos ventas.',
    ejemplos: [{ entrada: '10\n20\n5\n20\n30\n5\n10', salida: '100\n5\n3' }, { entrada: '8\n8\n8\n8\n8\n8\n8', salida: '56\n1\n1' }],
  },

  /* ── Matrices ── */
  {
    numero: 45, tema: 'matrices', nivel: 4,
    titulo: 'Suma por columnas',
    resumen: 'Recorrer la matriz de arriba hacia abajo.',
    descripcion: [
      'Una tabla guarda los goles de varios equipos: cada fila es una fecha del torneo y cada columna es un equipo.',
      'Lee la tabla y muestra cuántos goles anotó cada equipo en todo el torneo, es decir, la suma de cada columna, empezando por la primera.',
    ],
    entrada: 'Las dos primeras líneas traen F y C (entre 1 y 10). Siguen F por C líneas con un entero cada una: los elementos fila por fila, de izquierda a derecha.',
    salida: 'C líneas: la suma de cada columna, en orden.',
    ejemplos: [{ entrada: '2\n3\n1\n2\n3\n4\n5\n6', salida: '5\n7\n9' }, { entrada: '3\n1\n2\n0\n4', salida: '6' }],
  },
  {
    numero: 46, tema: 'matrices', nivel: 4,
    titulo: 'Girar la tabla',
    resumen: 'Las filas pasan a ser columnas.',
    descripcion: [
      'Trasponer una matriz es intercambiar sus filas con sus columnas: la primera fila se convierte en la primera columna, la segunda fila en la segunda columna, y así sucesivamente. Una matriz de F filas y C columnas queda con C filas y F columnas.',
      'Lee una matriz y muestra su traspuesta.',
    ],
    entrada: 'Las dos primeras líneas traen F y C (entre 1 y 10). Siguen F por C líneas con un entero cada una: los elementos fila por fila, de izquierda a derecha.',
    salida: 'F por C líneas con los elementos de la traspuesta, fila por fila y de izquierda a derecha.',
    ejemplos: [{ entrada: '2\n3\n1\n2\n3\n4\n5\n6', salida: '1\n4\n2\n5\n3\n6' }, { entrada: '1\n2\n7\n8', salida: '7\n8' }],
  },
  {
    numero: 47, tema: 'matrices', nivel: 5,
    titulo: 'Matriz espejo',
    resumen: 'Comparar cada casilla con su reflejo.',
    descripcion: [
      'Una matriz cuadrada es simétrica cuando funciona como un espejo respecto a su diagonal principal: el elemento de la fila i y la columna j es igual al de la fila j y la columna i, para todas las posiciones.',
      'Lee una matriz cuadrada e indica si es simétrica.',
    ],
    entrada: 'La primera línea trae N (entre 1 y 10). Siguen N por N líneas con un entero cada una: los elementos fila por fila, de izquierda a derecha.',
    salida: 'Una línea con Simetrica o No simetrica, sin tilde.',
    ejemplos: [{ entrada: '2\n1\n2\n2\n1', salida: 'Simetrica' }, { entrada: '2\n1\n2\n3\n1', salida: 'No simetrica' }, { entrada: '1\n5', salida: 'Simetrica' }],
  },
  {
    numero: 48, tema: 'matrices', nivel: 4,
    titulo: 'Las dos diagonales',
    resumen: 'Una diagonal baja hacia la derecha y la otra hacia la izquierda.',
    descripcion: [
      'Una matriz cuadrada tiene dos diagonales. La principal va de la esquina superior izquierda a la inferior derecha. La secundaria va de la esquina superior derecha a la inferior izquierda.',
      'Lee una matriz cuadrada y muestra la suma de cada diagonal.',
    ],
    entrada: 'La primera línea trae N (entre 1 y 10). Siguen N por N líneas con un entero cada una: los elementos fila por fila, de izquierda a derecha.',
    salida: 'Dos líneas: la suma de la diagonal principal y la suma de la diagonal secundaria.',
    ejemplos: [{ entrada: '3\n1\n2\n3\n4\n5\n6\n7\n8\n9', salida: '15\n15' }, { entrada: '2\n1\n0\n5\n2', salida: '3\n5' }, { entrada: '1\n4', salida: '4\n4' }],
  },
  {
    numero: 49, tema: 'matrices', nivel: 5,
    titulo: 'El mejor vendedor',
    resumen: 'Un total por fila y el mayor de esos totales.',
    descripcion: [
      'Una empresa registra las ventas de sus vendedores en una tabla: cada fila es un vendedor y cada columna es un mes.',
      'Lee la tabla y encuentra al vendedor con mayor venta total. Muestra el número de su fila, contando desde 1, y cuánto vendió. Si varios empatan en el primer lugar, gana el que aparece primero en la tabla.',
    ],
    entrada: 'Las dos primeras líneas traen F y C (entre 1 y 10). Siguen F por C líneas con un entero mayor o igual que cero cada una: los elementos fila por fila, de izquierda a derecha.',
    salida: 'Dos líneas: el número de la fila ganadora y su venta total.',
    ejemplos: [{ entrada: '2\n3\n1\n2\n3\n4\n5\n6', salida: '2\n15' }, { entrada: '3\n2\n5\n5\n1\n1\n10\n0', salida: '1\n10' }],
  },
  {
    numero: 50, tema: 'matrices', nivel: 5,
    titulo: 'Tres en raya',
    resumen: 'Revisar filas, columnas y diagonales.',
    descripcion: [
      'El tablero de tres en raya es una matriz de 3 por 3. Cada casilla vale 0 si está vacía, 1 si la marcó el primer jugador y 2 si la marcó el segundo. Gana quien tenga sus tres marcas en línea: en una fila, en una columna o en cualquiera de las dos diagonales.',
      'Lee el tablero e indica quién ganó. En los tableros de este ejercicio nunca ganan los dos a la vez.',
    ],
    entrada: 'Nueve líneas con un entero entre 0 y 2 cada una: las casillas fila por fila, de izquierda a derecha.',
    salida: 'Una línea con Gana 1, Gana 2 o Sin ganador.',
    ejemplos: [{ entrada: '1\n1\n1\n0\n2\n2\n0\n0\n0', salida: 'Gana 1' }, { entrada: '2\n1\n0\n1\n2\n0\n1\n0\n2', salida: 'Gana 2' }, { entrada: '1\n2\n1\n2\n1\n2\n2\n1\n2', salida: 'Sin ganador' }, { entrada: '0\n2\n1\n0\n2\n1\n0\n2\n0', salida: 'Gana 2' }],
  },
];
